apiVersion: v1
kind: Service
metadata:
  name: rivian-prometheus-exporter-service
spec:
  selector:
    app: rivian-prometheus-exporter
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8000